// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPGSIds
{
        public const string achievement_witch_master = "CgkItN-m2agSEAIQDA"; // <GPGSID>
        public const string achievement_unknown2 = "CgkItN-m2agSEAIQBA"; // <GPGSID>
        public const string event_event = "CgkItN-m2agSEAIQBw"; // <GPGSID>
        public const string achievement_unknown = "CgkItN-m2agSEAIQBQ"; // <GPGSID>
        public const string achievement_1000_kills = "CgkItN-m2agSEAIQDw"; // <GPGSID>
        public const string leaderboard_kills = "CgkItN-m2agSEAIQBg"; // <GPGSID>
        public const string achievement_10000_kills = "CgkItN-m2agSEAIQDQ"; // <GPGSID>
        public const string achievement_stage1_clear = "CgkItN-m2agSEAIQCw"; // <GPGSID>
        public const string achievement_unknown1 = "CgkItN-m2agSEAIQAQ"; // <GPGSID>

}

